TecoRP_Website/Models/Applications.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecoRP_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applications()
        {
            this.Answers = new HashSet<Answers>();
        }
    
        public int ApplicationId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Name { get; set; }
        public string SocialClubName { get; set; }
        public string Contact { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answers> Answers { get; set; }
    }
}

TecoRP_Website/Areas/AdminPanel/Controllers/ApplicationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using TecoRP_Website.Models;

namespace TecoRP_Website.Areas.AdminPanel.Controllers
{
    [Authorize(Roles ="Admin")]
    public class ApplicationController : Controller
    {
        private TecoRPEntities db = new TecoRPEntities();

        // GET: AdminPanel/Applications
        public ActionResult Index(string filter)
        {
            switch (filter)
            {
                case "awaiting":
                    return View(db.Applications.Where(w=>w.IsApproved == null).ToList());
                case "approved":
                    return View(db.Applications.Where(w => w.IsApproved == true).ToList());
                case "rejected":
                    return View(db.Applications.Where(w => w.IsApproved == false).ToList());

                default:
                    return View(db.Applications.ToList());
            }
        }

        // GET: AdminPanel/Applications/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applications applications = db.Applications.Find(id);
            if (applications == null)
            {
                return HttpNotFound();
            }

            ApplicationViewModel viewModel = new ApplicationViewModel();
            var user = db.AspNetUsers.Find(applications.UserID);

            viewModel.ApplicationID = applications.ApplicationId;
            viewModel.Email = user.Email;
            viewModel.SocialClubName = user.SocialClubName;
            viewModel.RegisterDate = (DateTime)applications.RegisterDate;
            viewModel.IsApproved = applications.IsApproved;
            foreach (var item in applications.Answers)
            {
                viewModel.Answers.Add(new AnswerField {
                    AnswerSelection=(int)item.Answer,
                    AnswerText = item.AnswerText,
                    QuestionId = item.QuestionId,
                    QuestionText = item.Questions.QuestionText,
                    Selection_A = item.Questions.Selection_A,
                    Selection_B = item.Questions.Selection_B,
                    Selection_C = item.Questions.Selection_C,
                    IsTextArea = item.Questions.IsTextArea,
                });
            }
            return View(viewModel);
        }

        public ActionResult ApproveStatus(int id, bool? status)
        {
            var application = db.Applications.Find(id);
            if (application!=null)
            {
                string param = "";
                switch (application.IsApproved)
                {
                    case null:
                        param = "awaiting";
                        break;
                    case true:
                        param = "approved";
                        break;
                    case false:
                        param = "rejected";
                        break;
                }
                //if (status==true)
                //{
                //    var user = db.AspNetUsers.Find(User.Identity.GetUserId());
                //    TecoRP.Database.db_WhiteList.AddPlayer(user.SocialClubName,true);
                //}
                application.IsApproved = status;
                db.SaveChanges();
                return RedirectToAction("Index", new { filter = param });
            }
            return RedirectToAction("Index");
        }
        // GET: AdminPanel/Applications/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applications applications = db.Applications.Find(id);
            if (applications == null)
            {
                return HttpNotFound();
            }
            return View(applications);
        }

        // POST: AdminPanel/Applications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ApplicationId,IsApproved,Name,SocialClubName,Contact,UserID,RegisterDate")] Applications applications)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applications).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applications);
        }

        // GET: AdminPanel/Applications/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applications applications = db.Applications.Find(id);
            if (applications == null)
            {
                return HttpNotFound();
            }
            return View(applications);
        }

        // POST: AdminPanel/Applications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Applications applications = db.Applications.Find(id);
            db.Applications.Remove(applications);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TecoRP_Website/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using TecoRP_Website.Models;

namespace TecoRP_Website.Controllers
{
    [Authorize]
    public class ApplicationsController : Controller
    {
        private TecoRPEntities db = new TecoRPEntities();

        //// GET: Applications
        //public ActionResult Index()
        //{
        //    var applications = db.Applications.FirstOrDefault(x => x.UserID == User.Identity.GetUserId());
        //    if (applications == null)
        //    {
        //        return RedirectToAction("New");
        //    }
        //    return View(db.Applications.ToList());
        //}

        // GET: Applications/Details/5
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();

            var application = db.Applications.FirstOrDefault(x => x.UserID == userId );
            if (application == null)
            {
                return RedirectToAction("New");
            } 
            return View(application);
        }

        // GET: Applications/Create
        public ActionResult New(string param)
        {
            var user = db.AspNetUsers.Find(User.Identity.GetUserId());
            if (String.IsNullOrEmpty(user.SocialClubName))
            {
                return RedirectToAction("Configuration", "Home");
            }
            if (param=="new")
            {
                var userId = User.Identity.GetUserId();
                var app = db.Applications.FirstOrDefault(x => x.UserID == userId);
                app.Answers.Clear();
                db.Applications.Remove(app);
                db.SaveChanges();
            }
            ApplicationModel appModel = new Models.ApplicationModel();
            Random r = new Random();
            var question = db.Questions.ToList().OrderBy(x=>Guid.NewGuid());
            foreach (var item in question)
            {
                appModel.Answers.Add(new AnswerField(item.QuestionID, item.QuestionText, item.IsTextArea, item.Selection_A, item.Selection_B, item.Selection_C));
            }
            if (appModel.Answers.Count <=0)
            {
                return RedirectToAction("Index","Home");
            }
            return View(appModel);
        }

        // POST: Applications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult New([Bind(Include = "Answers")] ApplicationModel application)
        {     

            var user = db.AspNetUsers.Find(User.Identity.GetUserId());
            if (String.IsNullOrEmpty(user.SocialClubName))
            {
                return RedirectToAction("Configuration", "Home", new { Area = "" });
            }

            var app = new Applications
            {
                UserID = user.Id,
                Name = user.Email,
                SocialClubName = user.SocialClubName,
                RegisterDate = DateTime.Now,
            };

            foreach (var item in application.Answers)
            {
                app.Answers.Add(new Answers
                {
                    Answer = (byte)item.AnswerSelection,
                    AnswerText = item.AnswerText,
                    Questions = db.Questions.Find(item.QuestionId)
                });
            }
            db.Applications.Add(app);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Applications/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applications applications = db.Applications.Find(id);
            if (applications == null)
            {
                return HttpNotFound();
            }
            return View(applications);
        }

        // POST: Applications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ApplicationId,IsApproved,Name,SocialClubName,Contact,UserID,RegisterDate")] Applications applications)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applications).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applications);
        }

        // GET: Applications/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applications applications = db.Applications.Find(id);
            if (applications == null)
            {
                return HttpNotFound();
            }
            return View(applications);
        }

        // POST: Applications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Applications applications = db.Applications.Find(id);
            db.Applications.Remove(applications);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TecoRP_Website/Views/Applications/Delete.cshtml
@model TecoRP_Website.Models.Applications

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Applications</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IsApproved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsApproved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SocialClubName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SocialClubName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisterDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisterDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TecoRP_Website/Views/Applications/Edit.cshtml
@model TecoRP_Website.Models.Applications

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Applications</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ApplicationId)

        <div class="form-group">
            @Html.LabelFor(model => model.IsApproved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsApproved)
                    @Html.ValidationMessageFor(model => model.IsApproved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SocialClubName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SocialClubName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SocialClubName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegisterDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegisterDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegisterDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TecoRP_Website/Views/Applications/Index.cshtml
@model TecoRP_Website.Models.Applications

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@switch (Model.IsApproved)
{
    case null:
        <div class="demo-cards mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-grid mdl-grid--no-spacing">
            <div class="demo-updates mdl-card mdl-shadow--2dp mdl-cell mdl-cell--4-col mdl-cell--12-col-tablet mdl-cell--12-col-desktop">
                <div style="background-image:url(/Content/images/basvuru.png);" class="mdl-card__title mdl-card--expand mdl-color--yellow-A200">
                    <h2 class="mdl-card__title-text">Onay Bekliyor</h2>
                </div>
                <div class="mdl-card__supporting-text mdl-color-text--grey-600">
                    @Convert.ToDateTime(Model.RegisterDate).ToString("dd.MM.yyyy") tarihli başvurunuz onay bekliyor.
                </div>
              
            </div>
            <div class="demo-separator mdl-cell--1-col"></div>
        </div>
        break;
    case true:
        <div class="demo-cards mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-grid mdl-grid--no-spacing">
            <div class="demo-updates mdl-card mdl-shadow--2dp mdl-cell mdl-cell--4-col mdl-cell--12-col-tablet mdl-cell--12-col-desktop">
                <div style="background-image:url(/Content/images/basvuru.png);" class="mdl-card__title mdl-card--expand mdl-color--green-A200">
                    <h2 class="mdl-card__title-text">ONAYLANDI</h2>
                </div>
                <div class="mdl-card__supporting-text mdl-color-text--grey-600">
                    @Convert.ToDateTime(Model.RegisterDate).ToString("dd.MM.yyyy") tarihli başvurunuz onaylanmıştır.<br />
                    <b>@Model.SocialClubName</b> adlı social club üyeliğiniz ile oyuna giriş yapabilirsiniz. <br />
                    <hr />
                    Oyuna <b>185.122.202.58</b> adresinden veya <b>server.teco-rp.com</b> adresi üzerinden <b>4499</b> portuyla bağlanabilirsiniz.
                </div>

            </div>
            <div class="demo-separator mdl-cell--1-col"></div>
        </div>
        break;
    case false:
        <div class="demo-cards mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-grid mdl-grid--no-spacing">
            <div class="demo-updates mdl-card mdl-shadow--2dp mdl-cell mdl-cell--4-col mdl-cell--12-col-tablet mdl-cell--12-col-desktop">
                <div style="background-image:url(/Content/images/basvuru.png);" class="mdl-card__title mdl-card--expand mdl-color--red-900">
                    <h2 class="mdl-card__title-text">Reddedildi.</h2>
                </div>
                <div class="mdl-card__supporting-text mdl-color-text--grey-600">
                    @Convert.ToDateTime(Model.RegisterDate).ToString("dd.MM.yyyy") tarihli başvurunuz maalesef reddedilmiş. Ama üzülmen gerek yok. Hemen yeni bir başvuruda bulunabilirsin.<br />
                    
                   <p>Social club hesabınız link veya url olarak girildiğinden dolayı başvurunuz reddedilmiş olabilir.<br />
                    Bunu çözmek için @Html.ActionLink("buraya","Configuration","Home") tıklayabilirsiniz.
                    </p>                
                   
                </div>
                <div class="mdl-card__actions mdl-card--border">
                    <a href="@Url.Action("New","Applications",new { param="new" })" class="mdl-button mdl-js-button mdl-js-ripple-effect" data-upgraded=",MaterialButton,MaterialRipple">
                        YENİ BAŞVURU
                        <span class="mdl-button__ripple-container"><span class="mdl-ripple"></span></span>
                    </a>
                </div>
            </div>
            <div class="demo-separator mdl-cell--1-col"></div>
        </div>
        break;
    default:
        break;
}

TecoRP_Website/Views/Applications/New.cshtml
@model TecoRP_Website.Models.ApplicationModel

@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    
    <div class="mdl-grid demo-content">

        @for (int i = 0; i < Model.Answers.Count; i++)
        {
            @Html.HiddenFor(model => model.Answers[i].QuestionId)
        <div class="demo-cards mdl-cell mdl-cell--6-col mdl-cell--12-col-tablet mdl-grid mdl-grid--no-spacing">
            <div class="demo-updates mdl-card mdl-shadow--2dp mdl-cell mdl-cell--4-col mdl-cell--12-col-tablet mdl-cell--12-col-desktop">
                <div style="background-image:url(/Content/images/soru.png);" class="mdl-card__title mdl-card--expand mdl-color--purple-400">
                    <h1 class="mdl-card__title-text">SORU</h1>
                </div>
                <div class="mdl-card__supporting-text mdl-color-text--grey-600">
                   <h2 style="font-size:larger"> @Model.Answers[i].QuestionText </h2> <br>                       
                 </div>
                <div class="mdl-card__supporting-text mdl-color-text--grey-400">
                    @if (Model.Answers[i].IsTextArea)
                    {
                        @Html.TextAreaFor(model => model.Answers[i].AnswerText,new { @cols="50" })
                    }
                    else
                    {
                        @Html.RadioButtonFor(model => model.Answers[i].AnswerSelection, 0, new { @class = "mdl-radio__button" })
                        <span> @Model.Answers[i].Selection_A </span> <br />
                        @Html.RadioButtonFor(model => model.Answers[i].AnswerSelection, 1)
                        <span> @Model.Answers[i].Selection_B </span> <br />
                        @Html.RadioButtonFor(model => model.Answers[i].AnswerSelection, 2)
                        <span> @Model.Answers[i].Selection_C </span> <br />
                        <hr />
                    }


                    <br>
                </div>
            </div>
            <div class="demo-separator mdl-cell--1-col"></div>
        </div>

        }



        <div class="demo-cards mdl-cell mdl-cell--12-col mdl-cell--8-col-tablet mdl-grid mdl-grid--no-spacing">
            <div style="min-height: 36px;" class="demo-updates mdl-card mdl-shadow--2dp mdl-cell mdl-cell--4-col mdl-cell--4-col-tablet mdl-cell--12-col-desktop">


                <input type="submit" value="GÖNDER" class="mdl-button mdl-js-button mdl-js-ripple-effect" />

            </div>
        </div>

    </div>


    


        


}